# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master


strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.14'
    win-2019:
       imageName: 'windows-2019'
    Windows-core:
       imagename: 'win1803'

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

# does not help 
# - script: |
#     npm install pwsh -g
#   displayName: 'npm install pwsh'

- script: |
    npm install
  displayName: 'npm install'


- script: |
    npm run X-postinstall
  displayName: 'post'

- script: |
    npm run hello1
  displayName: 'hello 1'



- script: |
    npm run build
  displayName: 'npm build'

- script: |
    npm run package-prep
  displayName: 'npm prepare for vscode package'

- script: |
    npm test
  displayName: 'npm test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'XUnit'
    testResultsFiles: '**/TEST-*.xml'
    mergeTestResults: true
    displayName: 'Publish Test results'

- script: |
    npm run package
  displayName: 'npm package'

- task: CopyFiles@1
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
    
      *.vsix
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
